eureka:
  client:
    register-with-eureka: true    # 👈 corrected (was "registry-with-eureka")
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
